name: Laravel Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key and test connection
        run: |
          set -e
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 45.9.190.92 >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          rsync -avz -e "ssh -p 22" ./forestry/ root@45.9.190.92:/var/www/forestry/
